#!/usr/bin/env python3
"""Export judge-readable artifacts from the deterministic replay outcome."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from contextpatch.models import to_dict
from contextpatch.replay import run_replay
from contextpatch.writeback import apply_local_replay_write_back


GENERATED_AT = "2026-07-18T10:25:02Z"


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repository-root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    root = args.repository_root.resolve()
    outcome = run_replay(root)
    reports = root / "examples" / "reports"
    patches = root / "examples" / "patches"
    generated = root / "examples" / "generated-artifacts"

    provenance = {
        "synthetic": True,
        "generatedBy": "contextpatch-deterministic-mock-v1",
        "generatedAt": GENERATED_AT,
        "sourceIncident": outcome.incident["incidentId"],
        "contextSnapshot": "recorded-datahub-context-replay",
        "validationStatus": outcome.validation.final_status,
    }
    write_json(reports / "impact-analysis.json", {**provenance, "impactGraph": to_dict(outcome.impact_graph)})
    write_json(reports / "validation-result.json", {**provenance, "validation": to_dict(outcome.validation)})
    write_json(
        reports / "write-back-result.json",
        {
            **provenance,
            "boundary": "Local replay store only; no DataHub mutation was attempted.",
            "result": apply_local_replay_write_back(
                outcome.write_back_preview,
                {"approved": True, "patchId": outcome.patch_plan.patch_id},
                root / "artifacts" / "runtime" / "example-local-writeback.json",
            ),
        },
    )

    combined_diff = "".join(file.diff for file in outcome.patch_plan.files)
    patches.mkdir(parents=True, exist_ok=True)
    proposed_header = (
        "# synthetic example\n"
        "# generated by: contextpatch-deterministic-mock-v1\n"
        f"# generated at: {GENERATED_AT}\n"
        f"# source incident: {outcome.incident['incidentId']}\n"
        "# context: recorded DataHub context replay\n"
        "# approval: pending\n\n"
    )
    approved_header = proposed_header.replace("# approval: pending", "# approval: replay-demo-approved; not applied to repository or DataHub")
    (patches / "proposed.patch").write_text(proposed_header + combined_diff, encoding="utf-8")
    (patches / "approved.patch").write_text(approved_header + combined_diff, encoding="utf-8")

    migration_source = (generated / "2026-07-dsp-schema-change.md").read_text(encoding="utf-8")
    (generated / "migration-report.md").write_text(
        "<!-- synthetic: true; generated-by: contextpatch-deterministic-mock-v1; "
        f"generated-at: {GENERATED_AT}; source-incident: {outcome.incident['incidentId']}; "
        "context: recorded-datahub-context-replay; validation: passed -->\n\n" + migration_source,
        encoding="utf-8",
    )
    (reports / "incident-resolution.md").write_text(
        "# Synthetic incident resolution\n\n"
        f"- Generated by: `contextpatch-deterministic-mock-v1`\n"
        f"- Generated at: `{GENERATED_AT}`\n"
        f"- Source incident: `{outcome.incident['incidentId']}`\n"
        "- Context: recorded DataHub context replay\n"
        f"- Validation: `{outcome.validation.final_status}`\n"
        "- External mutations: none\n\n"
        "The replay mapped `artist_share` to `rights_split_pct`, normalized mixed fraction/percentage units, "
        "mapped `net_amount` to `payable_revenue`, identified the bounded downstream payout lineage, and "
        "generated an eight-file patch plan. The patch passed policy, fixture, reconciliation, and isolated "
        "dbt/DuckDB validation. The included write-back result is a local replay record only.\n",
        encoding="utf-8",
    )
    print("Exported replay examples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
